version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: segment-storage
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: segment-api
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      ENV: ${ENV}
      HTTP_PORT: ${HTTP_PORT}
      HTTP_HOST: ${HTTP_HOST}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"

volumes:
  postgres_data: